### PR TITLE
Whole Swathe of Translations #8

### PR DESCRIPTION
**Pull request by KomradeSpectre**
Sorry yet again for the messy commit history :c
Translated the entirety of Simple_Text.xml, and did a few fixes/additions to other files.
Still have yet to finish the dungeon clues, but seeing as they're useless (since the guide for that stuff is out and people use that instead) they'll be on the backburner for a while.

### CODE REVIEW

**Comment by riftcrystal** [comment]
Could you double-check "どこにですか？" and "答えたいですが、表現がわかりません"?

You didn't translate them, but they were flagged as possibly being wrong and never got adjusted.

I will go ahead and merge this in. If those happen to need changing make a new pull request and I can get them in.

**Comment by riftcrystal** [comment]
This turned into commit fac6afa with a forced update.

**Comment by KomradeSpectre** [comment]
Which file were those?

**Comment by KomradeSpectre** [comment]
どこにですか (Doko ni desu ka)  is correct as is. It does mean Where to? Since Doko is where/what place and ni is a particle that when added on acts to indicate a destination, and finally desu is a polite ending to the sentence with the ka making the sentence a question.

**Comment by KomradeSpectre** [comment]
The second one is only technically wrong. I'll submit a change on that one.

**Comment by riftcrystal** [comment]
@KomradeSpectre Thank you.

**Pull request merged**
