### PR TITLE
Lore

### PR DESCRIPTION
**Pull request by Lasria**
The rest of season 3.0s Joseph lore notes. Not sure if I should refer the 悪しき竜 as Evil Dragon or Wicked Dragon. Other areas in translation refer to him as Evil but official romaji that came out with season 3.3 info calls him the Wicked Dragon. I kept it as Evil Dragon for consistency for now.

### CODE REVIEW

**Comment by riftcrystal** [comment]
Do you have a reference link for the official romaji referring to it as the Wicked Dragon? If that is the case, then the preference here would be Wicked Dragon.

**Review by riftcrystal — CHANGES_REQUESTED** [review]
Make "Evil Dragon" to "Wicked Dragon" if that is the official romaji.

**Comment by phuclagger** [comment]
It was in the Famitsu magazine

**Comment by riftcrystal** [comment]
Thank you. Please use "Wicked Dragon".

**Pull request merged**
